name: Drum-kit

on: push

jobs:
  drum-kit:
    name: drumkit code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Run Drumkit
        uses: github/Drumkit@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
